name: Deploy brntn.me

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - build 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install commonmark
      run: |
        python3 -m pip install commonmark
    - name: Build website
      run: |
        python3 build.py
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build
